@startuml 数据库现状
hide empty description
left to right direction
state visit as "操作"
state database {
    state first as "NowMonthTable0" {
        state data1 as "ActivityData0"
        state data2 as "ActivityData1"
        state data3 as "ActivityData2"
        state datamore as "..."
    }
    state second as "MonthTable1" {
        state sdata1 as "ActivityData0"
        state sdata2 as "ActivityData1"
        state sdata3 as "ActivityData2"
        state sdatamore as "..."
    }
    state third as "MonthTable2" {
        state tdata1 as "ActivityData0"
        state tdata2 as "ActivityData1"
        state tdata3 as "ActivityData2"
        state tdatamore as "..."
    }
    state more as "..."
}
visit --> first : 占了绝大部分
visit --> second : 小部分
visit --> third : 小部分
visit --> more : 小部分
@enduml

@startuml 按月分库
hide empty description
state op as "操作"
state db1 {
   state NowMonth
   state Month1
   state Month2
}
state db2 {
   state Month3 as "Month"
   state Month4 as "Month"
   state Month5 as "Month"
}
op --> NowMonth : 绝大部分
op --> Month1 : 小部分
op --> Month2 : 小部分
op --> Month3 : 小部分
op --> Month4 : 小部分
op --> Month5 : 小部分
@enduml

@startuml 按活动分库
hide empty description
state op as "操作"
state db1 {
   state NowMonth {
       state activity1 #LightCyan
   }
   state Month1
   state Month2
}
state db2 {
   state Month3 as "NowMonth" {
       state activity2 #LightCyan
   }
   state Month4 as "Month1"
   state Month5 as "Month2"
}
op --> NowMonth : 大部分
op --> Month1 : 小部分
op --> Month2 : 小部分
op --> Month3 : 大部分
op --> Month4 : 小部分
op --> Month5 : 小部分
@enduml