@startuml 数据库现状
hide empty description
left to right direction
state visit as "操作"
state database {
    state first as "NowMonthTable0" {
        state data1 as "ActivityData0"
        state data2 as "ActivityData1"
        state data3 as "ActivityData2"
        state datamore as "..."
    }
    state second as "MonthTable1" {
        state sdata1 as "ActivityData0"
        state sdata2 as "ActivityData1"
        state sdata3 as "ActivityData2"
        state sdatamore as "..."
    }
    state third as "MonthTable2" {
        state tdata1 as "ActivityData0"
        state tdata2 as "ActivityData1"
        state tdata3 as "ActivityData2"
        state tdatamore as "..."
    }
    state more as "..."
}
visit --> first : 占了绝大部分
visit --> second : 小部分
visit --> third : 小部分
visit --> more : 小部分
@enduml

@startuml 按月分库
hide empty description
state op as "操作"
state db1 {
   state NowMonth
   state Month1
   state Month2
}
state db2 {
   state Month3 as "Month"
   state Month4 as "Month"
   state Month5 as "Month"
}
op --> NowMonth : 绝大部分
op --> Month1 : 小部分
op --> Month2 : 小部分
op --> Month3 : 小部分
op --> Month4 : 小部分
op --> Month5 : 小部分
@enduml

@startuml 按活动分库
hide empty description
state op as "操作"
state db1 {
   state NowMonth {
       state activity1 #LightCyan
   }
   state Month1
   state Month2
}
state db2 {
   state Month3 as "NowMonth" {
       state activity2 #LightCyan
   }
   state Month4 as "Month1"
   state Month5 as "Month2"
}
op --> NowMonth : 大部分
op --> Month1 : 小部分
op --> Month2 : 小部分
op --> Month3 : 大部分
op --> Month4 : 小部分
op --> Month5 : 小部分
@enduml

@startuml 单数据操作流量图
hide empty description
state op as "用户操作"
state service as "业务应用"
state db as "分片库" #LightPink {
    state proxy
    state mysql0
    state mysql1
    state mysql2
    proxy --> mysql0 : 分库策略
    proxy --> mysql1 : 分库策略
    proxy --> mysql2 : 分库策略
}
op -> service
service -> proxy : 带上分库key
@enduml

@startuml 多数据操作流量图
hide empty description
state op as "用户操作"
state service as "业务应用" {
    state ops as "拆分成多个单库操作"
    state trans as "业务保证事务性质"
    state op1 as "分片键1"
    state op2 as "分片键2"
    state op3 as "分片键3"
    ops -> trans
    trans --> op1
    trans --> op2
    trans --> op3
}
state db as "分片库" #LightPink {
    state proxy
    state mysql0
    state mysql1
    state mysql2
    proxy --> mysql0 : 分库策略
    proxy --> mysql1 : 分库策略
    proxy --> mysql2 : 分库策略
}
op -> service
op1 --> proxy : 带上分库key
op2 --> proxy : 带上分库key
op3 --> proxy : 带上分库key
@enduml